# Generated by Django 3.1.3 on 2021-09-09 17:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
    ]
